//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRHeader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRHeader()
        {
            this.PRApprover = new HashSet<PRApprover>();
            this.PRItem = new HashSet<PRItem>();
        }
    
        public int Id { get; set; }
        public string PrNo { get; set; }
        public string PrDate { get; set; }
        public string Requester { get; set; }
        public string Dept { get; set; }
        public string ApproveStatus { get; set; }
        public string CreatedAt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRApprover> PRApprover { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRItem> PRItem { get; set; }
    }
}
